# Generated by Django 5.2.7 on 2025-10-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(default='TEMP0001', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
