# Generated by Django 5.2.7 on 2025-10-03 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_employee_employee_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='catalog.brand'),
        ),
    ]
